version: 2
updates:
  - package-ecosystem: "npm" # 
    directory: "/journalapp/frontend" 
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "pip" 
    directory: "/journalapp/backend" 
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
