db:
    image: postgres:latest
    environment:
      POSTGRES_DB: journal
      POSTGRES_USER: andrew
      DB_HOST: db
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./dumps:/dumps
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

create_table:
  build: ./backend
  command: python manage.py createcachetable
  depends_on:
    db:
      condition: service_healthy

  migrate:
    build: ./backend
    command: python manage.py migrate
    depends_on:
      - create_table

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - migrate