version: 2.1

jobs:
  build_backend:
    docker:
      - image: cimg/python:3.10.14
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: journal
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      SECRET_KEY: $SECRET_KEY
      DB_NAME: journal
      DB_USER: circleci
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: localhost
      DB_PORT: 5432
      FIREBASE_CREDENTIALS_BASE64: $FIREBASE_CREDENTIALS_BASE64
    working_directory: ~/journalapp/backend
    steps:
      - checkout:
          path: ~/journalapp
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Create Firebase credentials file
          command: |
            if [ -n "$FIREBASE_CREDENTIALS_BASE64" ]; then
              echo $FIREBASE_CREDENTIALS_BASE64 | base64 --decode > firebase-creds.json
            fi
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run Migrations
          command: |
            . venv/bin/activate
            python manage.py migrate --no-input
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python manage.py test --verbosity=2

  build_frontend:
    docker:
      - image: cypress/base:16.13.0
    working_directory: ~/journalapp/frontend
    steps:
      - checkout:
          path: ~/journalapp
      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package.json" }}
            - v1-npm-dependencies-
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-npm-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build Frontend
          command: npm run build || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_backend