# Generated by Django 5.0.6 on 2024-07-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.category'),
        ),
    ]
