# Generated by Django 5.0.6 on 2024-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journalentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='most_recent_entry',
            field=models.BooleanField(default=False),
        ),
    ]
