# Generated by Django 5.0.6 on 2024-07-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_journalentry_most_recent_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='most_recent_entry',
        ),
    ]
