# Generated by Django 5.0.6 on 2024-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_remove_journalentry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='image',
            new_name='content_image',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='content',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
