name: Auto Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (for npm projects)
        uses: actions/setup-node@v3
        with:
          node-version: '16' 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Merge PR
        uses: actions-ecosystem/action-merge@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash 

- name: Approve PR
  uses: hmarr/auto-approve-action@v3
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
  if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
